"""initial_migration

Revision ID: bc04d8f85be0
Revises: 
Create Date: 2026-04-04 22:19:17.176434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc04d8f85be0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruption_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('disruption_score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('severity_multiplier', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disruption_events'))
    )
    with op.batch_alter_table('disruption_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disruption_events_id'), ['id'], unique=False)

    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.String(length=10), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('avg_weekly_income', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_riders'))
    )
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_riders_rider_external_id'), ['rider_external_id'], unique=True)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('disruption_event_id', sa.Integer(), nullable=True),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('disruption_score', sa.Float(), nullable=True),
    sa.Column('behavior_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('payout_amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disruption_event_id'], ['disruption_events.id'], name=op.f('fk_claims_disruption_event_id_disruption_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_claims_rider_id_riders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('claim_number', name=op.f('uq_claims_claim_number'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_disruption_event_id'), ['disruption_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_rider_id'), ['rider_id'], unique=False)

    op.create_table('disruption_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disruption_event_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disruption_event_id'], ['disruption_events.id'], name=op.f('fk_disruption_signals_disruption_event_id_disruption_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disruption_signals'))
    )
    with op.batch_alter_table('disruption_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disruption_signals_disruption_event_id'), ['disruption_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disruption_signals_id'), ['id'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('premium_amount', sa.Float(), nullable=False),
    sa.Column('coverage_amount', sa.Float(), nullable=False),
    sa.Column('city_tier', sa.String(length=10), nullable=True),
    sa.Column('base_premium_pct', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_policies_rider_id_riders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('policy_number', name=op.f('uq_policies_policy_number'))
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_rider_id'), ['rider_id'], unique=False)

    op.create_table('rider_behavior_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('temporal_score', sa.Float(), nullable=True),
    sa.Column('spatial_score', sa.Float(), nullable=True),
    sa.Column('activity_score', sa.Float(), nullable=True),
    sa.Column('overall_behavior_score', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_rider_behavior_logs_rider_id_riders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rider_behavior_logs'))
    )
    with op.batch_alter_table('rider_behavior_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_behavior_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rider_behavior_logs_rider_id'), ['rider_id'], unique=False)

    op.create_table('fusion_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('disruption_score', sa.Float(), nullable=False),
    sa.Column('behavior_score', sa.Float(), nullable=False),
    sa.Column('risk_weight', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('past_claims_count', sa.Integer(), nullable=True),
    sa.Column('zone_risk', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_fusion_decisions_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fusion_decisions'))
    )
    with op.batch_alter_table('fusion_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fusion_decisions_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fusion_decisions_id'), ['id'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_payouts_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_payouts_rider_id_riders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_rider_id'), ['rider_id'], unique=False)

    op.create_table('premium_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('previous_premium', sa.Float(), nullable=True),
    sa.Column('new_premium', sa.Float(), nullable=False),
    sa.Column('change_reason', sa.String(length=200), nullable=True),
    sa.Column('weekly_income', sa.Float(), nullable=True),
    sa.Column('zone_risk', sa.Float(), nullable=True),
    sa.Column('claim_history_count', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_premium_history_policy_id_policies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_premium_history_rider_id_riders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_premium_history'))
    )
    with op.batch_alter_table('premium_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_premium_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_history_rider_id'), ['rider_id'], unique=False)

    op.create_table('post_event_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('previous_risk_score', sa.Float(), nullable=True),
    sa.Column('new_risk_score', sa.Float(), nullable=True),
    sa.Column('previous_premium', sa.Float(), nullable=True),
    sa.Column('new_premium', sa.Float(), nullable=True),
    sa.Column('previous_zone_risk', sa.Float(), nullable=True),
    sa.Column('new_zone_risk', sa.Float(), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_post_event_updates_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], name=op.f('fk_post_event_updates_payout_id_payouts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_post_event_updates_rider_id_riders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_event_updates'))
    )
    with op.batch_alter_table('post_event_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_event_updates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_event_updates_rider_id'), ['rider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_event_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_event_updates_rider_id'))
        batch_op.drop_index(batch_op.f('ix_post_event_updates_id'))

    op.drop_table('post_event_updates')
    with op.batch_alter_table('premium_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_premium_history_rider_id'))
        batch_op.drop_index(batch_op.f('ix_premium_history_id'))

    op.drop_table('premium_history')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_rider_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_claim_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('fusion_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fusion_decisions_id'))
        batch_op.drop_index(batch_op.f('ix_fusion_decisions_claim_id'))

    op.drop_table('fusion_decisions')
    with op.batch_alter_table('rider_behavior_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rider_behavior_logs_rider_id'))
        batch_op.drop_index(batch_op.f('ix_rider_behavior_logs_id'))

    op.drop_table('rider_behavior_logs')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_rider_id'))
        batch_op.drop_index(batch_op.f('ix_policies_id'))

    op.drop_table('policies')
    with op.batch_alter_table('disruption_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disruption_signals_id'))
        batch_op.drop_index(batch_op.f('ix_disruption_signals_disruption_event_id'))

    op.drop_table('disruption_signals')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_rider_id'))
        batch_op.drop_index(batch_op.f('ix_claims_id'))
        batch_op.drop_index(batch_op.f('ix_claims_disruption_event_id'))

    op.drop_table('claims')
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riders_rider_external_id'))
        batch_op.drop_index(batch_op.f('ix_riders_id'))

    op.drop_table('riders')
    with op.batch_alter_table('disruption_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disruption_events_id'))

    op.drop_table('disruption_events')
    # ### end Alembic commands ###
